#!/usr/bin/bash

# Display the time for 12 hours and 59 minutes using while loop

hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done
    minute=1
    ((hour++))
done

