int _putchar(char c);
void print_alphabet (void);
void print_to_98(int n);
void time_table(void);
void print_alphabet_x10(void);
int abs(int);
void print_times_table(int n);
int add(int, int);
int print_last_digit(int);
int print_sign(int n);
int _isalpha(int c);
int _islower(int c);
